console.log("");
console.log('opencc installed — the "opencc" command is now available anywhere.');
console.log("");
console.log("  opencc init             Configure settings (one-time, from the terminal)");
console.log("  opencc                  Start the proxy server");
console.log("  opencc claude [args]    Launch Claude Code, pointed at the proxy");
console.log("");
console.log('First run: "opencc init" to set up your API key and model, then run');
console.log('"opencc" in one terminal and "opencc claude" in another.');
console.log("");
